### ISSUE TITLE
Provides setter methods

### ISSUE THREAD

**Issue by KasumiNova** [Krutoy242/D.zs#1]

**Comment by Krutoy242** [comment]
I don't understand.
Can you cite an example?

**Comment by KasumiNova** [comment]
Allows the user to modify the content of the IData.
For example: setInt("key", 9);

**Comment by Krutoy242** [comment]
Nice idea, thanks. I will consider to do that

**Comment by friendlyhj** [comment]
In most cases, `IData` is immutable, the `setXXX` method is not available. If you want to create a new modified IData, just call the `update` method of `IData`.
For example, `data.update({key: 9})`

**Comment by Krutoy242** [comment]
Yeah, but this won't work with long path.
```
"path.to[0].deep"
```

**Comment by Krutoy242** [comment]
Closing issue since this functionality was implemented by [ZenUtils](https://github.com/friendlyhj/ZenUtils/wiki/DeepDataUpdate) mod.
